# Generated by Django 4.1 on 2022-08-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_comment_image_alter_post_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilepic',
            field=models.ImageField(default='users/default.png', upload_to='users/'),
        ),
    ]
